### ISSUE TITLE
Roadmap to Gremlins.js 2.0

### ISSUE THREAD

**Issue by HALLERPierre** [marmelab/gremlins.js#133]
# Roadmap to Gremlins 2.0

Gremlins.js is now older than 6 years old and the last commit is 2 year old. We think it’s time to give some love to this useful and fun package !

That’s with this gold in mind that @zyhou and @HALLERPierre are the new maintainers of this project.

Our first goal is to give a new youth to gremlins.js. Say goodbye to callbacks hell and say hello to promises and async functions !

But we won’t stop here, here is the **roadmap to Gremlins** v2 :

- [ ] Conventional commit and changelog
- [ ] Update dependency
	- [ ] eslint/prettier
	- [ ] chance
	- [ ] babel
	- [ ] webpack
- [ ] Add unit and integration tests
- [ ] Improve build
	- [ ] cjs, esm, mjs
	- [ ] Polyfill
- [ ] Deploy and CI
	- [ ] Deployment automation
	- [ ] Continuous integration
	- [ ] Bookmarktlet 
- [ ] Refacto
	- [ ] Use promises instead of callbacks
	- [ ] Refresh javascript style (es6)
	- [ ] Improve config injection
  - [ ] Improve horde creation
- [ ] Readme and Documentation
	- [ ] Update Readme
	- [ ] Update Documentation
	- [ ] Expose Gremlins in console (like lodash/datefns)
	- [ ] Contribution
	- [ ] jsdoc
- [ ] Exemples
	- [ ] useful ?
	- [ ] Inside Documentation?
	- [ ] React/Angular/VueJS, etc…
- [ ] Communication release
	- [ ] Issues grooming
	- [ ] New issue
	- [ ] Article on Marmelab blog

This will lead to a deep transformation of the library.

Before releasing a stable version, we'll publish next releases. Development has already started and is visible on the next branch. We tag related pull request with the 2.0 milestone so you can track our progress.

Comments and contributing are welcome.

**Comment by HALLERPierre** [comment]
Here is the PR of the new version of Gremlins :
https://github.com/marmelab/gremlins.js/pull/157

**Comment by stof** [comment]
The changelog does not describe any BC break in 2.0. I find this confusing.
